# Site Settings
title: Tania's tutorial
email: rene.tigerstedt@gmail.com
description: >
  My first Jekyll Theme
baseurl: "/tanias-theme"
url: "http://tigerre1.github.io"
twitter_username: RTigerstedt
github_username:  tigerre1
# Build Settings

include: ['_pages']
kramdown:
  input: GFM
gem: [jekyll-admin]
