# Site Settings
title: Taina's tutorial
email: rene.tigerstedt@gmail.com
description: >
  My first Jekyll Theme
baseurl: ""
url: "http://localhost:4000"
twitter_username: RTigerstedt
github_username:  tigerre1
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM