# Site Settings
title: Enterin tietoiskupankki
email: rene.tigerstedt@gmail.com
description: >
  My first Jekyll Theme
baseurl: ''
url: "http://tigerre1.github.io"
twitter_username: RTigerstedt
github_username:  tigerre1
# Build Settings

include: ['_pages']
kramdown:
  input: GFM
gem: [jekyll-admin]
